name: Lint
on:
  pull_request:
  workflow_dispatch:
  push:
    branches: main

jobs:
  lint_python:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install .[test]

      - name: Lint with Flake8
        run: |
          python3 -m venv .venv
          . .venv/bin/activate

          flake8 --statistics .
